<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string></string>
	</array>
	<key>name</key>
	<string>Dalvik Classes (Androguard)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>package</string>
			<key>match</key>
			<string>^([\w\d\_/\$]+)</string>
			<key>name</key>
			<string>storage.package</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>current class</string>
			<key>match</key>
			<string>^(\s*[\w\d\_/\$]+)(\s*)(extends)(\s*)(.)*</string>
			<key>name</key>
			<string>storage.class</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>init/clinit method</string>
			<key>match</key>
			<string>^(\s*(method\:))(\s*)((\&lt;init\&gt;)|(\&lt;clinit\&gt;))(.)+</string>
			<key>name</key>
			<string>support</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>method</string>
			<key>match</key>
			<string>^(\s*(method\:))(.)+</string>
			<key>name</key>
			<string>support.function.classicmethod</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>field</string>
			<key>match</key>
			<string>^(\s*(field\:))(.)+</string>
			<key>name</key>
			<string>variable</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ag</string>
	<key>uuid</key>
	<string>75ba8e42-b55b-4823-b4aa-e4e407da9c8d</string>
</dict>
</plist>
