name: Keep clone up to date
variables:
  REMOTE_ADDR: 'https://github.com/keatkean/Mobile-Security-Framework-MobSF.git'
stages:
  - stage: running_git_commands
    displayName: running_git_commands
    jobs:
      - job: initiate
        displayName: initiate
        continueOnError: false
        steps:
        - checkout: self
          clean: true
          persistCredentials: true
          displayName: run_commands
        - bash: | 
            git checkout Development
            git remote add Mobile-Security-Framework-MobSF $(REMOTE_ADDR)
            git fetch Mobile-Security-Framework-MobSF Development
            git reset --hard Mobile-Security-Framework-MobSF/Development
            git pull --rebase Mobile-Security-Framework-MobSF Development
            git push -f origin