# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-11-30 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticanalyzerandroid',
            name='MD5',
            field=models.CharField(max_length=32),
        ),
    ]
