# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticanalyzerandroid',
            name='ICON_FOUND',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staticanalyzerandroid',
            name='ICON_HIDDEN',
            field=models.BooleanField(default=False),
        ),
    ]
