# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2017-01-11 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticanalyzerioszip',
            name='PERMISSIONS',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
