# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-11-30 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaticAnalyzer', '0002_auto_20161130_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticanalyzerioszip',
            name='MD5',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='staticanalyzeripa',
            name='MD5',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='staticanalyzerwindows',
            name='MD5',
            field=models.CharField(max_length=32),
        ),
    ]
