version: "3.8"
services:
  web:
    image: opensecurity/mobile-security-framework-mobsf:latest
    hostname: mobsfhost
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - webnet
networks:
  webnet:
