# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentScansDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.TextField()),
                ('MD5', models.CharField(max_length=50)),
                ('URL', models.TextField()),
                ('TS', models.DateTimeField()),
            ],
        ),
    ]
