name: 'Docker Images (amd64/arm64) test'

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
    buildx:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v7
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v4
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v4
        -
            name: Build AMD64 image
            id: docker_build_amd
            uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
            with:
                push: false
                provenance: false
                context: .
                platforms: linux/amd64
                tags: opensecurity/mobile-security-framework-mobsf:latest
        -
            name: Build ARM64 image
            id: docker_build_arm
            uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
            with:
                push: false
                provenance: false
                context: .
                platforms: linux/arm64
                tags: opensecurity/mobile-security-framework-mobsf:latest
