name: MobSF tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Host Dependencies
      run: |
        sudo apt update && sudo apt install -y openjdk-8-jdk libxml2-dev libxslt1-dev wkhtmltopdf
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel tox
        pip install --no-index --find-links=scripts/wheels yara-python || (pip wheel --wheel-dir=yara-python --build-option="build" --build-option="--enable-dex" "git+https://github.com/VirusTotal/yara-python.git@v3.11.0" && pip install --no-index --find-links=yara-python yara-python)
        pip install -r requirements.txt
    - name: Migrate and Setup Env
      run: |
        python manage.py makemigrations
        python manage.py makemigrations StaticAnalyzer
        python manage.py migrate
        git submodule update --init --recursive
    - name: Lint
      run: |
        tox -e lint
    - name: Unit Tests
      run: |
        python manage.py test
