name: MobSF tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Host Dependencies
      run: |
        sudo apt update && sudo apt install -y openjdk-8-jdk xfonts-75dpi xfonts-base
        export WKHTML_URL=https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/
        export WKHTML_DEB=wkhtmltox_0.12.6-1.bionic_amd64.deb
        wget ${WKHTML_URL}${WKHTML_DEB} && sudo dpkg -i ${WKHTML_DEB} && rm -rf ${WKHTML_DEB}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel tox
        pip install --no-index --find-links=scripts/wheels yara-python || (pip wheel --wheel-dir=yara-python --build-option="build" --build-option="--enable-dex" "git+https://github.com/VirusTotal/yara-python.git@v3.11.0" && pip install --no-index --find-links=yara-python yara-python)
        pip install -r requirements.txt
    - name: Migrate Database
      run: |
        python manage.py makemigrations
        python manage.py makemigrations StaticAnalyzer
        python manage.py migrate
    - name: Lint
      run: |
        tox -e lint
    - name: Unit Tests
      run: |
        git submodule update --init --recursive
        python manage.py test
